In [3]:
import numpy as np
import pandas as pd

complete_path = '../../data/processed/hi_rws_0001_0256_complete.csv'
topics_path = '../../data/processed/hi_rws_0001_0256_topics_selected.csv'
sentiments_path = '../../data/processed/hi_rws_0001_0256_sentiments.csv'

df1 = pd.read_csv(complete_path)
df2 = pd.read_csv(topics_path)
df3 = pd.read_csv(sentiments_path)

df1 = df1.drop(['sent_tokens', 'word_tokens', 'norm_tokens', 'sent_topics'], axis=1)
df1 = df1.drop(['word_tokens_doc', 'norm_tokens_doc'], axis=1)
df1 = df1.drop(['topic_mode', 'topic_list', 'svm_classifier'], axis=1)
df2 = df2.drop(['Unnamed: 0'], axis=1)
df3['sgd.1'].name = 'sentiment_score'

df = pd.concat([df1, df2, df3['sgd.1']], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195769 entries, 0 to 195768
Data columns (total 28 columns):
alias               195769 non-null object
ratingValue         195769 non-null int64
dataPublished       195769 non-null object
description         195769 non-null object
author              195769 non-null object
sentiment           195769 non-null int64
word_count          195769 non-null int64
sent_count          195769 non-null int64
chr_count           195769 non-null int64
avg_word_len        195769 non-null float64
avg_sent_len        195769 non-null float64
num_of_stopwords    195769 non-null int64
num_of_modals       195769 non-null int64
hashtags            195769 non-null int64
mentions            195769 non-null int64
numerics            195769 non-null int64
uppercase_cnt       195769 non-null int64
punctuation_cnt     195769 non-null int64
vocab_cnt           195769 non-null int64
ratio_lexical       195769 non-null float64
ratio_content       195769 non-null float64
topic_0             195769 non-null float64
topic_1             195769 non-null float64
topic_2             195769 non-null float64
topic_3             195769 non-null float64
topic_4             195769 non-null float64
topic_score         195769 non-null int64
sentiment_score     195769 non-null int64
dtypes: float64(9), int64(15), object(4)
memory usage: 41.8+ MB

In [4]:
df.head()

,alias,ratingValue,dataPublished,description,author,sentiment,word_count,sent_count,chr_count,avg_word_len,...,vocab_cnt,ratio_lexical,ratio_content,topic_0,topic_1,topic_2,topic_3,topic_4,topic_score,sentiment_score
0,kimos-maui-lahaina,5,2019-01-06,I stumbled across this great restaurant overlo...,Bella L.,1,135,11,664,4.022222,...,76,0.637037,0.674074,1.0,5.0,2.0,1.0,2.0,1,1
1,kimos-maui-lahaina,5,2019-01-04,Excellent view on the ocean at sunset.\nExcell...,Rachou A.,1,36,5,160,3.611111,...,25,0.777778,0.638889,1.0,1.0,1.0,1.0,1.0,4,1
2,kimos-maui-lahaina,3,2018-12-25,This place was not what the reviews portrayed ...,Ozzetta B.,0,275,14,1229,3.596364,...,130,0.534545,0.567273,2.0,4.0,3.0,0.0,5.0,4,0
3,kimos-maui-lahaina,2,2018-12-08,We were excited to repeat our Keoki's (in Kaua...,Arleen C.,0,475,34,2226,3.783158,...,206,0.484211,0.604211,8.0,8.0,7.0,2.0,9.0,4,0
4,kimos-maui-lahaina,3,2018-11-29,"If you're looking for a tourist spot, this is ...",Carol B.,0,168,10,776,3.732143,...,97,0.648810,0.636905,1.0,3.0,2.0,1.0,3.0,1,0

In [19]:
df.to_csv('../../data/processed/hi_rws_0001_0256_final.csv', index=False)